# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge of `JOIN` statements, using various types of joins and various methods for specifying the links between them.

## Objectives

You will be able to:

* Write SQL queries that make use of various types of joins
* Compare and contrast the various types of joins
* Discuss how primary and foreign keys are used in SQL
* Decide and perform whichever type of join is best for retrieving desired data

## CRM ERD

In this lab, you'll use the same customer relationship management (CRM) database that you saw from the previous lesson.
<img src='https://curriculum-content.s3.amazonaws.com/data-science/images/Database-Schema.png' width="600">

## Connecting to the Database
Import the necessary packages and connect to the database `'data.sqlite'`.

In [1]:
# Your code here
import pandas as pd
import sqlite3
conn = sqlite3.connect('data.sqlite')
curr = conn.cursor()

In [2]:
curr.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = curr.fetchall()
print(tables)

[('productlines',), ('offices',), ('customers',), ('employees',), ('orderdetails',), ('orders',), ('payments',), ('products',)]

In [3]:
pd.read_sql("""SELECT * FROM offices""", conn).head()

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
2,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
3,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
4,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan

In [4]:
pd.read_sql("""SELECT * FROM employees""", conn).head()

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)

In [5]:
pd.read_sql("""SELECT * FROM orders""", conn).head()

,orderNumber,orderDate,requiredDate,shippedDate,status,comments,customerNumber
0,10100,2003-01-06,2003-01-13,2003-01-10,Shipped,,363
1,10101,2003-01-09,2003-01-18,2003-01-11,Shipped,Check on availability.,128
2,10102,2003-01-10,2003-01-18,2003-01-14,Shipped,,181
3,10103,2003-01-29,2003-02-07,2003-02-02,Shipped,,121
4,10104,2003-01-31,2003-02-09,2003-02-01,Shipped,,141

In [18]:
pd.read_sql("""SELECT * FROM products""", conn).head()

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00

In [20]:

pd.read_sql("""SELECT * FROM orderdetails""", conn).head()

   orderNumber productCode  quantityOrdered  priceEach  orderLineNumber
0        10100    S18_1749               30     136.00                3
1        10100    S18_2248               50      55.09                2
2        10100    S18_4409               22      75.46                4
3        10100    S24_3969               49      35.29                1
4        10101    S18_2325               25     108.06                4

## Select the names of all employees in Boston 

Hint: join the employees and offices tables. Select the first and last name.

In [6]:
# Your code here
pd.read_sql("""SELECT firstName, lastName FROM employees
JOIN offices ON employees.officeCode = offices.officeCode
WHERE offices.city = "Boston"
GROUP BY offices.city
""", conn)

  firstName  lastName
0     Julie  Firrelli

## Are there any offices that have zero employees?
Hint: Combine the employees and offices tables and use a group by. Select the office code, city, and number of employees.

In [7]:
# Your code here
pd.read_sql("""SELECT employees.employeeNumber, employees.officeCode, offices.city FROM employees
JOIN offices ON employees.officeCode
WHERE employeeNumber IS NULL
GROUP BY offices.officeCode
""" ,conn)

Empty DataFrame
Columns: [employeeNumber, officeCode, city]
Index: []

## Write 3 questions of your own and answer them

In [17]:
# Answers will vary

# Example question: 
"""
How many customers are there per office?

"""

pd.read_sql("""SELECT offices.city, COUNT(customers.customerNumber) AS count_customers FROM offices
JOIN customers ON offices.officecode
GROUP BY offices.city

""",conn)

            city  count_customers
0         Boston              244
1         London              122
2            NYC              122
3          Paris              122
4  San Francisco              122
5         Sydney              122
6          Tokyo              122

In [9]:
"""
number of employees per country 
"""

# Your code here
pd.read_sql("""SELECT offices.country, COUNT(employees.employeeNumber) AS employeeCount FROM employees
JOIN offices ON employees.officeCode = offices.officeCode
GROUP BY country

""" ,conn)

     country  employeeCount
0  Australia              4
1     France              5
2      Japan              2
3         UK              2
4        USA             10

In [12]:
"""
which country has the most orders
"""

# Your code here
pd.read_sql("""SELECT offices.country, COUNT(orders.orderNumber) AS count_orderNumber FROM offices
JOIN orders ON offices.officeCode
GROUP BY offices.country
ORDER BY count_orderNumber DESC

""",conn)

     country  count_orderNumber
0        USA               1304
1         UK                326
2      Japan                326
3     France                326
4  Australia                326

In [29]:
"""
Question 3
"""

# Your code here

'\nQuestion 3\n'

## Level Up 1: Display the names of every individual product that each employee has sold

Hint: You will need to use multiple `JOIN` clauses to connect all the way from employee names to product names.

In [30]:
# Your code here
pd.read_sql("""SELECT products.productName, employees.lastName, employees.firstName FROM employees
JOIN products ON employees.officeCode
GROUP BY productName
""" ,conn)

                             productName lastName firstName
0    18th Century Vintage Horse Carriage   Murphy     Diane
1                  18th century schooner   Murphy     Diane
2                 1900s Vintage Bi-Plane   Murphy     Diane
3                1900s Vintage Tri-Plane   Murphy     Diane
4                      1903 Ford Model A   Murphy     Diane
..                                   ...      ...       ...
105                        The Mayflower   Murphy     Diane
106                       The Queen Mary   Murphy     Diane
107                The Schooner Bluenose   Murphy     Diane
108                          The Titanic   Murphy     Diane
109            The USS Constitution Ship   Murphy     Diane

[110 rows x 3 columns]

## Level Up 2: Display the number of products each employee has sold

Alphabetize the results by employee last name.

Hint: Use the `quantityOrdered` column from `orderDetails`. Also, think about how to group the data when some employees might have the same first or last name.

In [46]:
# Your code here
pd.read_sql("""SELECT COUNT(orders.orderNumber) AS products_sold, employees.lastName, employees.firstName FROM employees
JOIN orders ON employees.officeCode
GROUP BY firstName, lastName
ORDER BY products_sold DESC
""" ,conn)

    products_sold   lastName firstName
0             326     Fixter      Andy
1             326        Bow   Anthony
2             326      Jones     Barry
3             326     Murphy     Diane
4             326      Tseng  Foon Yue
5             326     Vanauf    George
6             326     Bondur    Gerard
7             326  Hernandez    Gerard
8             326   Firrelli      Jeff
9             326   Firrelli     Julie
10            326       Bott     Larry
11            326   Jennings    Leslie
12            326   Thompson    Leslie
13            326     Bondur      Loui
14            326      Nishi      Mami
15            326     Gerard    Martin
16            326  Patterson      Mary
17            326   Castillo    Pamela
18            326      Marsh     Peter
19            326  Patterson     Steve
20            326       King       Tom
21            326  Patterson   William
22            326       Kato   Yoshimi

## Level Up 3: Display the names employees who have sold more than 200 different products

Hint: this is different from the previous question because the quantity sold doesn't matter, only the number of different products

In [60]:
# Your code here
pd.read_sql("""SELECT COUNT(orders.orderNumber) AS products_sold, employees.lastName, employees.firstName FROM employees
JOIN orders ON employees.officeCode
GROUP BY employees.firstName, employees.lastName
HAVING products_sold >= 200 
ORDER BY products_sold DESC

""" ,conn)

    products_sold   lastName firstName
0             326     Fixter      Andy
1             326        Bow   Anthony
2             326      Jones     Barry
3             326     Murphy     Diane
4             326      Tseng  Foon Yue
5             326     Vanauf    George
6             326     Bondur    Gerard
7             326  Hernandez    Gerard
8             326   Firrelli      Jeff
9             326   Firrelli     Julie
10            326       Bott     Larry
11            326   Jennings    Leslie
12            326   Thompson    Leslie
13            326     Bondur      Loui
14            326      Nishi      Mami
15            326     Gerard    Martin
16            326  Patterson      Mary
17            326   Castillo    Pamela
18            326      Marsh     Peter
19            326  Patterson     Steve
20            326       King       Tom
21            326  Patterson   William
22            326       Kato   Yoshimi

## Summary

Congrats! You practiced using join statements and leveraged your foreign keys knowledge!